<?php

namespace Myapp\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends EntityRepository
{
       public function findAllAgence()
{
   
    return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CroisiereBundle:Agence p ORDER BY p.id ASC'
            )
        ->setMaxResults(5)
        ->setFirstResult(0)
        ->getResult();
    
}
}
