<?php

namespace Myapp\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BateauTypeCabineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateauTypeCabineRepository extends EntityRepository
{
   
    
    
    public function findByBateau()
{

       
    $qb = $this->createQueryBuilder('p');
     $qb->where('p.id =:id')
      ->setParameter('id', 1);

// Puis on filtre sur le nom des catégories à l'aide d'un IN
    
  return $qb->getQuery()
            ->getResult();

}

    
}
