<?php

namespace Myapp\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateauRepository extends EntityRepository
{
   
    
    
    public function findByIdJoinedToAgence($idAgence)
{
    

    
   
    
    $qb = $this->createQueryBuilder('a');
  $qb->where('a.agence = :agence')
      ->setParameter('agence', $idAgence);
    
  return $qb->getQuery()
            ->getResult();
  
   
}

    
    public function findByIdJoinedToBateau($idBateau)
{
    

    
   
    
    $qb = $this->createQueryBuilder('a');
  $qb->where('a.id = :id')
      ->setParameter('id', $idBateau);
    
  return $qb->getQuery()
            ->getResult();
  
   
}
    
}
