<?php

namespace Myapp\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CroisiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CroisiereRepository extends EntityRepository
{
     public function findByIdJoinedToBateau($idBateau)
{
    

    
   
    
            $qb = $this->createQueryBuilder('a');
            $qb->where('a.Bateau = :bateau')
              ->setParameter('bateau', $idBateau);

            return $qb->getQuery()
                      ->getResult();
}
       public function findAllCroisiere($page)
{
   
    return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CroisiereBundle:Croisiere p ORDER BY p.id ASC'
            )
        ->setMaxResults(4)
        ->setFirstResult($page)
        ->getResult();
    
}
    
    
}
