parameters:
#    croisiere.example.class: Myapp\CroisiereBundle\Example

services:
#    croisiere.example:
#        class: %croisiere.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
